### ISSUE TITLE
README Description

### ISSUE THREAD

**Issue by Max-Lev** [clarkio/node-web-push#3]
Hi, can you please add some description to use this setup? 
I am trying to receive notification from 'push' endpoint but getting 'bad request' response. Is there should be some data that should return from 'subscription' endpoint?

**Comment by isaacnass** [comment]
@Max-Lev 

hey hope you made some progress on this! If not, check this out:

If you go the `web-push`'s npm package they give an example of how to use this in the browser. [You have to convert the base64'd string that the server sends. ](https://www.npmjs.com/package/web-push#using-vapid-key-for-applicationserverkey)

Let me know if that helps!

**Comment by clarkio** [comment]
Hey, @Max-Lev and @isaacnass thank you for your interest in this repo and for taking the time to comment here. I was using this project as something to run with while working on a blog series. I've updated the README to reflect this in #4. I hope that helps give some more context and help get you past the issue you are seeing.

If it does not please feel free to re-open this issue and we can discuss further. 

Thanks again,
Brian
